---
title: "mirdeep_analysis"
author: "Brecia Douglas"
date: "2024-02-02"
output: github_document
---

File with mirdeep analysis

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = FALSE, fig.path='Figures/', dev=c('png', 'pdf'))
options(knitr.table.format = 'markdown')
options(scipen=10000)
```

Loading in R packages
```{r}
library(tidyverse)
library(kableExtra)
library(UpSetR)
library(ggplot2)
library(ggupset)
library(ComplexUpset)
```

Read in mirdeep files
```{r}
adi <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_30_38.csv")
ami <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_31_38.csv")
avi <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_34_02.csv")
eca <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_35_03.csv")
epa <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_36_03.csv")
hma <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_37_03.csv")
mse <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_38_04.csv")
nve <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_39_03.csv")
sca <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_40_04.csv")
spi <- read.csv("~/Desktop/RNA_Analysis_Lab/RNA_Analysis/mirdeep_files/result_23_04_2023_t_12_41_04.csv")

#need to add in 3 jellyfish, hco and cja
```

Creating combined file with all conserved species
```{r}
adi_sub <- adi %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_adi = example_miRBase_miRNA_with_the_same_seed)

ami_sub <- ami %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_ami = example_miRBase_miRNA_with_the_same_seed)

avi_sub <- avi %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_avi = example_miRBase_miRNA_with_the_same_seed)

eca_sub <- eca %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_eca = example_miRBase_miRNA_with_the_same_seed)

epa_sub <- epa %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_epa = example_miRBase_miRNA_with_the_same_seed)

hma_sub <- hma %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_hma = example_miRBase_miRNA_with_the_same_seed)

mse_sub <- mse %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_mse = example_miRBase_miRNA_with_the_same_seed)

nve_sub <- nve %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_nve = example_miRBase_miRNA_with_the_same_seed)

sca_sub <- sca %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_sca = example_miRBase_miRNA_with_the_same_seed)

spi_sub <- spi %>%
  select("provisional_id", "example_miRBase_miRNA_with_the_same_seed") %>%
  rename(miRNA_spi = example_miRBase_miRNA_with_the_same_seed)

all_species_list <- list(adi_sub, ami_sub, avi_sub, eca_sub, epa_sub, hma_sub, mse_sub, nve_sub, sca_sub, spi_sub)

all_sp_merge <- all_species_list %>%
  reduce(full_join, by="provisional_id") %>%
  na.omit()
```

Common miRNA appear in at least 4 of the 11 species
```{r}
common_id <- all_sp_merge %>%
  mutate(n_missing = rowSums(all_sp_merge == "-")) %>%
  filter(n_missing <= 7) %>%
  slice(-c(12:16)) %>%
  select(provisional_id)

all_sp_merge_sub <- all_sp_merge %>%
  mutate(n_missing = rowSums(all_sp_merge == "-")) %>%
  filter(n_missing <= 7) %>%
  slice(-c(12:16)) %>%
  rename(miRNA_ace = provisional_id) %>%
  mutate(common_name_miRNA = c(100, 2023, 9473, 2026, 2050, 2030, 9425, 2025, 2037, 2036, 2022)) %>%
  arrange(common_name_miRNA) %>%
  select(., -n_missing) 

all_sp_merge_sub$common_name_miRNA <- as.character(all_sp_merge_sub$common_name_miRNA)  

common_full <- merge(adi, common_id, by="provisional_id") %>%
  select(provisional_id, consensus_mature_sequence) %>%
  mutate(common_name_miRNA = c(100, 2023, 9473, 2026, 2050, 2030, 9425, 2025, 2037, 2036, 2022)) %>%
  arrange(common_name_miRNA)

kable(common_full)
#write.csv(common_full, "~/Desktop/miRNA_Characterization/common_miRNAs.csv")
```

miRNA Filtering
```{r}
cerv_miRNA_all <- merge(adi, all_sp_merge, by="provisional_id", all.y = TRUE)

#significant randfold p-value (24 removed), miRNA_score > 10* (176 removed) and minimum of 10 reads (none removed, all had >10).
cerv_miRNA_filter <- cerv_miRNA_all %>%
  select(provisional_id, miRDeep2_score, total_read_count, mature_read_count, significant_randfold_p.value, consensus_mature_sequence, consensus_star_sequence) %>%
  filter(miRDeep2_score >= 10) %>%
  filter(significant_randfold_p.value == "yes") %>%
  filter(total_read_count >= 10)

#580 --> 380

#write.csv(cerv_miRNA_filter, "~/Desktop/cerv_miRNA_filter.csv")
```

Upset plots
```{r}
#upset plot of the 21 in cervicornis shared by other cnidarians
#39 novel to cervicornis
all_sp_merge %>%
  as_tibble %>%
  pivot_longer(cols = -provisional_id,
               names_to = 'species',
               values_to = 'their_name',
               names_prefix = 'miRNA_') %>%
  filter(their_name != '-') %>%
  group_by(provisional_id, species) %>%
  summarise(n_miRNA = n()) %>%
  summarise(n_species = list(species)) %>%
  
  ggplot(aes(x=n_species)) +
  geom_bar() +
  scale_x_upset() +
  theme_classic() +
  theme_combmatrix(combmatrix.label.extra_spacing = 10)
```

